wiki/encyclopedia/urls.py
from django.urls import path

from .views import show_entry, index, search, newEntry, edit_page, show_error

app_name = "wiki"

urlpatterns = [
    path("", index, name="index"),
    path("search/", search, name="search"),
    path("<str:title>", show_entry, name="entries"),
    path("new/", newEntry, name="new"),
    path("edit/<str:entry>", edit_page, name="edit"),
    path("error/<str:error_message>", show_error, name="error"),
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls")),

]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
import markdown2
from random import choice

from .util import list_entries, get_entry, save_entry

class SearchEntryForm(forms.Form):
    entry = forms.CharField(label='',
                            widget=forms.TextInput(attrs={'placeholder': 'Type here'}))


class NewEntryForm(forms.Form):
    title = forms.CharField(label='',
                            widget=forms.TextInput(attrs={'placeholder': 'Name of entry'}))
    content = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Type your content here', 
                                                           'style': 'width: 70%; height: 200px;'}), label='')


class EditEntryForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea, label="", help_text="")

# Return a list of entries that have a name containing a specified substring
def list_entries_that_search_text_presented_in_entry(search_text):
    return [entry for entry in list_entries() if search_text.casefold() in entry.casefold()]


# Return True if a given title already exists in the list of all entries
def title_of_entry_already_in_entries(title):
    return title.casefold() in [entry.casefold() for entry in list_entries()]

# Render the index page with a list
def index(request):
    return render(request, f"encyclopedia/index.html", {
        "entries": list_entries(),
        "form": SearchEntryForm(),
        "random_page": f'/wiki/{choice(list_entries())}'
    })

#  Render the search page allowing users to search for entries by title.

def search(request):
    if request.method == "POST":
        form = SearchEntryForm(request.POST)
        if form.is_valid():
            searched_query = form.cleaned_data["entry"]
            if title_of_entry_already_in_entries(searched_query):
                return HttpResponseRedirect(f'/wiki/{searched_query}')
            return show_search_results(request, searched_query)
    return render(request, f"encyclopedia/search.html", {
        "search": "Search on the left",
        "form": SearchEntryForm(),
        "random_page": f'/wiki/{choice(list_entries())}'
    })
#     Render the page for a specific entry.
def show_entry(request, title):
    if title_of_entry_already_in_entries(title):
        return render(request, "encyclopedia/entry.html", {
            "entry": markdown2.markdown(get_entry(title)),
            "page_title":    title,
            "form": SearchEntryForm(),
            "random_page": f'/wiki/{choice(list_entries())}'
        })
    return HttpResponseRedirect(reverse('wiki:error', args=(f"Requested entry '{title}' not exists",)))

#Render a page showing all entries whose title contains the search query.

def show_search_results(request, searched_query):
    matched_entries = list_entries_that_search_text_presented_in_entry(searched_query)
    if matched_entries:
        return render(request, "encyclopedia/searchResult.html", {
            "results": f"Results for your search '{searched_query}' are:",
            "matched_entries": matched_entries,
            "form": SearchEntryForm(),
            "random_page": f'/wiki/{choice(list_entries())}'
        })

    return render(request, "encyclopedia/search_result.html", {
        "results": f'There is no results for particular search: "{searched_query}"',
        "form": SearchEntryForm(),
        "random_page": f'/wiki/{choice(list_entries())}'
    })

#Create new entry
def newEntry(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            if title_of_entry_already_in_entries(title):
                return HttpResponseRedirect(reverse('wiki:error', args=("Entry already exist",)))
            save_entry(title, content)
            return HttpResponseRedirect(reverse('wiki:entries', args=(title,)))
    return render(request, "encyclopedia/newEntry.html", {
        "new_entry_form": NewEntryForm(),
        "form": SearchEntryForm(),
        "random_page": f'/wiki/{choice(list_entries())}'
    })

# Allows a user to edit an existing entry and returns a rendered template
def edit_page(request, entry):
    content = get_entry(entry)
    if request.method == "POST":
        form = EditEntryForm(request.POST)
        if form.is_valid():
            payload_content = form.cleaned_data["content"]
            save_entry(entry, payload_content)
            return HttpResponseRedirect(reverse('wiki:entries', args=(entry,)))
    return render(request, "encyclopedia/edit.html", {
        # initial value of textarea
        "edit_entry_form": EditEntryForm(initial={'content': content}, auto_id=False),
        "form": SearchEntryForm(),
        "random_page": f'/wiki/{choice(list_entries())}',
        "entry": entry,
    })


def show_error(request, error_message):
    return render(request, f"encyclopedia/error.html", {
        "error": error_message,
        "form": SearchEntryForm(),
        "random_page": f'/wiki/{choice(list_entries())}'
    })

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Entry {{ entry }}
{% endblock %}

{% block body %}
    <form style="margin-top: 10px" action="{% url 'wiki:edit' entry=entry %}"  method="POST">
        <label for="edit_entry_title">Edit entry with title "{{ entry }}":
        </label>
            {% csrf_token %}
        <div>{{ edit_entry_form}}</div>
        <input type="submit">
    </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block body %}
    {{ entry | safe }}
    <a href="edit/{{ page_title }}">Edit {{ page_title }}</a>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error page
{% endblock %}

{% block body %}
    <h1>ERROR:</h1>
    {{ error }}
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>
    <ul>
        {% for entry in entries %}
            <li><a href="/wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <img src="https://upload.wikimedia.org/wikipedia/en/thumb/8/80/Wikipedia-logo-v2.svg/1920px-Wikipedia-logo-v2.svg.png" alt="WikiLogo" class="img-fluid resize">
                <h2>Wiki</h2>
                    <div>
                        <form action="{% url 'wiki:search' %}" method="post">
                            {% csrf_token %}
                            {{ form }}
                            <input type="submit" value="Search">
                        </form>
                    </div>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{{ random_page }}">Random Page</a>
                </div>
                {% block nav %}
                {{ src | safe}}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/newEntry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Entry
{% endblock %}

{% block body %}
    <form action="{% url 'wiki:new' %}" method="post">
        {% csrf_token %}
        <label for="new_entry_title">Add new entry to wiki:<br></label>
            {{ new_entry_form }}
            <div class="form-submit">
                <input type="submit" value="Submit" >
            </div>
    </form>
{% endblock %}



wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search page
{% endblock %}

{% block body %}
    <h4>{{ search }}</h4>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/searchResult.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search result page
{% endblock %}

{% block body %}
    <h3>{{ results }}</h3>
    <ul>
        {% for entry in matched_entries %}
            <li><a href="/wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}